"""Agent 服务模块

提供 Agent 相关的数据模型、LLM 适配器、上下文构建器、工具系统和编排器。
"""

from .schemas import (
    AgentRequest,
    AgentResponse,
    ConversationHistory,
    ExecutionTrace,
    HostInfo,
    HostSummaryContext,
    LLMResponse,
    Message,
    ModelConfig,
    ModelProvider,
    ModelRole,
    Plan,
    PlanStatus,
    PlanStep,
    PlannerConfig,
    PlannerOutput,
    RoleModelConfig,
    SkillCall,
    SkillDefinition,
    SkillMatch,
    SkillParameter,
    SkillType,
    ToolCallRequest,
    ToolResult,
    PageInfo,
    PageSummaryContext,
)
from .llm_adapter import (
    BaseLLMAdapter,
    ClaudeAdapter,
    CustomAdapter,
    DeepSeekAdapter,
    LLMAdapterFactory,
    OpenAIAdapter,
    UnifiedLLMAdapter,
)
from .context_builder import (
    ContextBuilderFactory,
    HostSummaryBuilder,
    PageSummaryBuilder,
)
from .tool_registry import (
    AgentToolResult,
    BaseTool,
    ToolExecutor,
    ToolRegistry,
    ToolStatus,
    get_default_registry,
    load_mcp_tools,
)
from .tools import (
    register_command_tools,
    register_detection_tools,
    register_file_tools,
    register_log_tools,
    register_system_tools,
)
from .planner import (
    BasePlanner,
    RuleBasedPlanner,
    LLMPlanner,
    create_planner,
)
from .executor import (
    Executor,
    ExecutionResult,
    ExecutionStatus,
    StepExecution,
)
from .orchestrator import (
    AgentOrchestrator,
    FinalReport,
    OrchestratorStatus,
    StructuredResult,
    run_agent_task,
)
from .skills import (
    BaseSkill,
    SkillRegistry,
    SkillStep,
    get_default_skill_registry,
    register_builtin_skills,
)

__all__ = [
    "AgentOrchestrator",
    "AgentRequest",
    "AgentResponse",
    "AgentToolResult",
    "BaseLLMAdapter",
    "BasePlanner",
    "BaseSkill",
    "BaseTool",
    "ClaudeAdapter",
    "ContextBuilderFactory",
    "ConversationHistory",
    "CustomAdapter",
    "DeepSeekAdapter",
    "ExecutionResult",
    "ExecutionStatus",
    "ExecutionTrace",
    "Executor",
    "FinalReport",
    "HostInfo",
    "HostSummaryBuilder",
    "HostSummaryContext",
    "LLMAdapterFactory",
    "LLMPlanner",
    "LLMResponse",
    "Message",
    "ModelConfig",
    "ModelProvider",
    "ModelRole",
    "OpenAIAdapter",
    "OrchestratorStatus",
    "PageInfo",
    "PageSummaryBuilder",
    "PageSummaryContext",
    "Plan",
    "PlanStatus",
    "PlanStep",
    "PlannerConfig",
    "PlannerOutput",
    "RoleModelConfig",
    "RuleBasedPlanner",
    "SkillCall",
    "SkillDefinition",
    "SkillMatch",
    "SkillParameter",
    "SkillRegistry",
    "SkillStep",
    "SkillType",
    "StepExecution",
    "StructuredResult",
    "ToolCallRequest",
    "ToolExecutor",
    "ToolRegistry",
    "ToolResult",
    "ToolStatus",
    "UnifiedLLMAdapter",
    "create_planner",
    "get_default_registry",
    "get_default_skill_registry",
    "load_mcp_tools",
    "register_builtin_skills",
    "register_command_tools",
    "register_detection_tools",
    "register_file_tools",
    "register_log_tools",
    "register_system_tools",
    "run_agent_task",
]
